site_name: Nbdev-dev
nav:
    - Home: index.md
    - About: about.md
    - Docs:
      - CodeRunner: codeRunner.md
      - Documenter: documenter.md
      - Export: export.md
      - MakeDocs: makedocs.md
    - FAQ: faq.md
  
theme:
  name: material
  palette:
    primary: white
  font:
    text: Roboto
  logo: assets/nbdev.png
  favicon: assets/nbdev.png
  features:
    navigation.tabs
    
  markdown_extensions:
    - meta  
    - pymdownx.highlight:
        linenums: true
 
  plugins:
    - search  
    - tags

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/thecodingprojec

    - icon: fontawesome/brands/medium
      link: https://medium.com/ml-and-automation
    
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/satyabratapal
      
repo_url: https://github.com/sapal6/nbdev.jl.git
repo_name: nbdev.jl