### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

module CodeRunner
#export
import Pluto: Notebook, Cell, Configuration, Notebook, ServerSession, ClientSession, update_run!, Cell, WorkspaceManager

#export
import Pluto.PlutoRunner

#export
#TODO:how to clean the child processes spawned by this process.
#also, executing the notebook this way prevents the tests to be
#executed in the notebook

"""
> executecode(nb::Notebook)--> This function does the following
> * Take a notebook. 
> * Create a fake server, fake client etc.
> * Run the notebook cell by cell and update the notebook with the output.
"""
function executecode(nb::Notebook)
	fakeserver=ServerSession()
	fakeclient = ClientSession(:fake, nothing)
	fakeserver.connected_clients[fakeclient.id] = fakeclient
	
	fakeclient.connected_notebook = nb
	
	update_run!(fakeserver, nb, nb.cells)
	nb
end

end