### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

module Makedocs
#export
"""create the given path if not present"""
function makepath(path:: AbstractString)
	if !isdir(path)
		mkdir(path)
	else
		@warn "Path not created becasue it was already present."
	end
end

#export
"""
> mkdocs_yml()--> Creates a mkdocs.yml file
at the document root and fills it with initial
content.
"""
function mkdocs_yml(path:: AbstractString)
	mkdoc_yml = joinpath(path, "mkdocs.yml")
	if !isfile(mkdoc_yml)
	    touch(mkdoc_yml)
	else
		@warn "File not created because it was already present"
    end
	
end

#export
begin
"""
> newsitegen()--> Create required directory structure for hosting documents and the initial files(index.md and mkdocs.yml) if not already there.
"""
function newsitegen()
	path = joinpath(".","docs")
    makepath(path)
end
end

end