### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

module Make
#export
include("../src/Documenter.jl")

#export
function build(nbs_dir)
		Documenter.export2md(nbs_dir)
		Documenter.export2readme()
end

end