### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

module Make
#export
include("../src/Documenter.jl")

#export
function build(nbsdir)
		Documenter.export2md(nbsdir)
		Documenter.export2readme()
end

end