### A Nbdev script file ###
### Autogenerated file. Don't modify. ###

module Makedocs
#export
"""create the given path if not present"""
function makepath(path:: AbstractString)
	if !isdir(path)
		mkdir(path)
	else
		@warn "Path not created becasue it was already present."
	end
end

#export
begin
"""
> newsitegen()--> Create required directory structure for hosting documents and the initial files(index.md and mkdocs.yml) if not already there.
"""
function newsitegen()
	
	path = joinpath("../","docs/docs")
    makepath(path)
end
end

end