name: Nbdev

on:
  push:
    branches: 'master'

jobs:
  publish:
    name: "Nbdev Documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.5'
      - name: Install dependencies
        run: julia --color=yes --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        run: |
          mkdir gh-pages
          cd gh-pages
          julia --color=yes --project=.. -e 'using Publish; deploy("../nbdev.jl/Project.toml", label="dev")'
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Built by Nbdev.jl."
          git push